# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'src/Blog.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: $(project)

- task: PublishPipelineArtifact@1
  displayName: Share
  inputs:
    targetPath: '$(Pipeline.Workspace)/src/output'
    artifact: 'BlogOutput'
    publishLocation: 'pipeline'